
default :
	@echo gen generate pages 
	@echo serve serve a local version

gen :
	# github pages will only serve a subfolder with the option of docs
	# odd but whatever
	zola build -o docs/

serve :
	# Zola serve will create a temporary ./public directory
	zola serve

